# Generated by Django 5.2.17 on 2026-09-21 10:42

import django.core.validators
import django.db.models.deletion
import re
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('code', models.CharField(help_text='Masalan: module-01. Diskda papka nomi sifatida ishlatiladi.', max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message="code faqat harf, raqam, nuqta, pastki chiziq va defisdan iborat bo'lishi va harf yoki raqam bilan boshlanishi kerak", regex=re.compile('^[A-Za-z0-9][A-Za-z0-9._-]*$'))], verbose_name='Kod')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('order_index', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('owui_kb_id', models.CharField(blank=True, help_text='Modul uchun Open WebUI Knowledge Base identifikatori.', max_length=64, null=True, verbose_name='Open WebUI KB ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'db_table': 'modules',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('code', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message="code faqat harf, raqam, nuqta, pastki chiziq va defisdan iborat bo'lishi va harf yoki raqam bilan boshlanishi kerak", regex=re.compile('^[A-Za-z0-9][A-Za-z0-9._-]*$'))], verbose_name='Kod')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('order_index', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('module', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='catalog.module', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'db_table': 'topics',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('type', models.CharField(choices=[('presentation', 'Taqdimot'), ('questions', 'Savollar'), ('literature', 'Adabiyot')], default='literature', max_length=20, verbose_name='Turi')),
                ('raw_file_path', models.CharField(max_length=255, verbose_name="Manba fayl yo'li")),
                ('original_filename', models.CharField(max_length=300, verbose_name='Asl fayl nomi')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Fayl hajmi (bayt)')),
                ('file_hash', models.CharField(blank=True, help_text='Bir xil faylni ikki marta indekslamaslik uchun.', max_length=64, null=True, verbose_name='SHA-256')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('queued', 'Navbatda'), ('converting', 'Konvertatsiya qilinmoqda'), ('md_ready', 'Markdown tayyor'), ('uploading', 'Yuklanmoqda'), ('indexed', 'Indekslangan'), ('failed', 'Xatolik')], default='new', max_length=20, verbose_name='Holati')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xato matni')),
                ('md_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name="Markdown fayl yo'li")),
                ('chunk_count', models.IntegerField(default=0, verbose_name='Chunklar soni')),
                ('char_count', models.IntegerField(default=0, verbose_name='Belgilar soni')),
                ('detected_script', models.CharField(blank=True, max_length=30, null=True, verbose_name='Aniqlangan yozuv')),
                ('owui_file_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Open WebUI fayl ID')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='Indekslangan vaqt')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan')),
                ('topic', models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalog.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'db_table': 'materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=50, verbose_name='Bosqich')),
                ('level', models.CharField(choices=[('info', "Ma'lumot"), ('warn', 'Ogohlantirish'), ('error', 'Xato')], default='info', max_length=10, verbose_name='Daraja')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('material', models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='catalog.material', verbose_name='Material')),
                ('module', models.ForeignKey(blank=True, db_column='module_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='catalog.module', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Audit yozuvi',
                'verbose_name_plural': 'Audit yozuvlari',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='idx_audit_logs_created_at')],
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('module', 'code'), name='uq_topics_module_code'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['file_hash'], name='idx_materials_file_hash'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['status'], name='idx_materials_status'),
        ),
    ]
