# Generated by Django 5.2.17 on 2026-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_restore_uploaded_by_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="owui_model_id",
            field=models.CharField(
                blank=True,
                help_text="Faqat shu modul bilim bazasidan javob beradigan agent (model preset).",
                max_length=128,
                null=True,
                verbose_name="Open WebUI agent ID",
            ),
        ),
    ]
