# Generated by Django 5.2.17 on 2026-10-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_module_owui_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='extraction_method',
            field=models.CharField(blank=True, choices=[('text', 'Matn qatlami'), ('ocr', 'OCR'), ('mixed', 'Aralash')], help_text='Matn PDF ichidan olinganmi yoki skanerdan OCR qilinganmi.', max_length=10, null=True, verbose_name='Matn manbai'),
        ),
        migrations.AddField(
            model_name='material',
            name='force_ocr',
            field=models.BooleanField(default=False, help_text="Matn qatlami bo'lsa ham barcha sahifalar OCR qilinadi.", verbose_name='Majburiy OCR'),
        ),
        migrations.AddField(
            model_name='material',
            name='ocr_confidence',
            field=models.FloatField(blank=True, help_text="OCR qilingan sahifalardagi so'zlarning o'rtacha ishonch bali.", null=True, verbose_name='OCR ishonchi (%)'),
        ),
        migrations.AddField(
            model_name='material',
            name='ocr_languages',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='OCR tillari'),
        ),
        migrations.AddField(
            model_name='material',
            name='ocr_page_count',
            field=models.IntegerField(default=0, verbose_name='OCR sahifalar'),
        ),
        migrations.AddField(
            model_name='material',
            name='progress_message',
            field=models.CharField(blank=True, help_text='Uzoq konvertatsiya davomida, masalan: OCR 145/480 sahifa.', max_length=200, null=True, verbose_name='Jarayon'),
        ),
    ]
